import os , time , glob
from codecutils import decodestring

os.chdir ("E:\\FlutterProjects\\qr_gif_codec\\example\\android\\app\\src\\main\\res\\values\\INSTA")
from subprocess import call

localappdata = os.getenv ("LOCALAPPDATA")
folderpath = os.path.join (localappdata , "Instaloader")
# for f in glob.glob(os.path.join(localappdata,"*")):
#    os.remove(f)
# call("instaloader r______s_____love_____ _sherlynchopra_ egupta urvashirautela peace.of.rupali ___priyanka______yadav priyankayadav026 sangeeta_nayak palaktiwarii dishapatani imouniroy watersoul_official watersoulspam malaikaaroraofficial niasharma90 nehasharmaofficial norafatehi --login=shyam_it9193 --stories")
# call("instaloader r______s_____love_____ _sherlynchopra_ egupta urvashirautela niasharma90 peace.of.rupali ___priyanka______yadav priyankayadav026 palaktiwarii sangeeta_nayak dishapatani imouniroy watersoul_official norafatehi avneetkaur_13 nehasharmaofficial rajeswari.patra.9 --login=shyam_it9193 --fast-update --stories")
# call("instaloader peace.of.rupali palaktiwarii niasharma90 sangeeta_nayak dishapatani  --login=shyam_it9193 --stories")

call ("instaloader rajeswari.patra.9 --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader sangeeta_nayak --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader r______s_____love_____ --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader priyankayadav026 --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader priyankayadav0875 --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader priya.yadav__2 --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader im_priyankayadav_ --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
# call ("instaloader priyankayadav_5525 --login=shyam_it9193 --fast-update --stories")
# time.sleep (60)
call ("instaloader priya_nkayadav026 --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader priyanka_actor05 --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader ___priyanka______yadav --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader peace.of.rupali --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader sat.abdee --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader satabdeeeee --login=shyam_it9193 --fast-update --stories")
time.sleep (60)

call ("instaloader nehasharmaofficial --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader norafatehi --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader watersoul_official --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader avneetkaur_13 --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader palaktiwarii --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader imouniroy --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader dishapatani --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader egupta --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader _sherlynchopra_ --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader malaikaaroraofficial --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader niasharma90 --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader urvashirautela --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader _vaanikapoor_ --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader giorgia.andriani22 --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader jacquelienefernandez --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader mmoonstar --login=shyam_it9193 --fast-update --stories")
time.sleep (60)
call ("instaloader aishasharma25 --login=shyam_it9193 --fast-update --stories")
time.sleep (60)

call ("instaloader filmygyan --login=shyam_it9193 --fast-update --stories --no-posts")
time.sleep (60)
call ("instaloader bollywoodsocietyy --login=shyam_it9193 --fast-update --stories --no-posts")
time.sleep (60)
call ("instaloader viralbhayani --login=shyam_it9193 --fast-update --stories --no-posts")
time.sleep (60)
call ("instaloader bollywoodbubble --login=shyam_it9193 --fast-update --stories --no-posts")
time.sleep (60)
call ("instaloader instantbollywood --login=shyam_it9193 --fast-update --stories --no-posts")
time.sleep (60)
call ("instaloader filmymantramedia --login=shyam_it9193 --fast-update --stories --no-posts")
time.sleep (60)
call ("instaloader bollywoodirect --login=shyam_it9193 --fast-update --stories --no-posts")
time.sleep (60)
call ("instaloader voompla --login=shyam_it9193 --fast-update --stories --no-posts")
time.sleep (60)
call ("instaloader manav.manglani --login=shyam_it9193 --fast-update --stories --no-posts")

# call("instaloader #giorgiaandriani --login=shyam_it9193 --fast-update")
# time.sleep(60)
# call("instaloader imran_offiicial shaansshutterstop --login=shyam_it9193 --fast-update --stories --no-posts")

# call("instaloader mmoonstar --login=shyam_it9193 --stories")
#
