import os , time , glob
import sys

from codecutils import decodestring

os.chdir ("E:\\FlutterProjects\\qr_gif_codec\\example\\android\\app\\src\\main\\res\\values\\INSTA")
from subprocess import call
useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0"
timeout = 86400
skipAlways = True
skipSometimes = False
# for f in glob.glob(os.path.join(localappdata,"*")):
#    os.remove(f)
# call("instaloader r______s_____love_____ _sherlynchopra_ egupta urvashirautela peace.of.rupali ___priyanka______yadav priyankayadav026 sangeeta_nayak palaktiwarii dishapatani imouniroy watersoul_official watersoulspam malaikaaroraofficial niasharma90 nehasharmaofficial norafatehi --login=shyam_it9193 --stories")
# call("instaloader r______s_____love_____ _sherlynchopra_ egupta urvashirautela niasharma90 peace.of.rupali ___priyanka______yadav priyankayadav026 palaktiwarii sangeeta_nayak dishapatani imouniroy watersoul_official norafatehi avneetkaur_13 nehasharmaofficial rajeswari.patra.9 --login=shyam_it9193 --fast-update --stories")
# call("instaloader peace.of.rupali palaktiwarii niasharma90 sangeeta_nayak dishapatani  --login=shyam_it9193 --stories")
call ("instaloader rajeswari.patra.9 --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout , useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader priyankayadav0875 --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout , useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader priya.yadav__2 --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout , useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader im_priyankayadav_ --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout , useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
# call ("instaloader priyankayadav_5525 --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
# time.sleep(5)
call ("instaloader priya_nkayadav026 --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout , useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader priyanka_actor05 --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout , useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader sat.abdee --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout , useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader sangeeta_nayak --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader r______s_____love_____ --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader priyankayadav026 --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader ___priyanka______yadav --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader watersoulspam --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout , useragent))
time.sleep(5)
call ("instaloader peace.of.rupali --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader satabdeeeee --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)

call ("instaloader nehasharmaofficial --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader norafatehi --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader watersoul_official --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader avneetkaur_13 --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader palaktiwarii --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader imouniroy --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader dishapatani --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader egupta --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader _sherlynchopra_ --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader malaikaaroraofficial --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader niasharma90 --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader urvashirautela --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader _vaanikapoor_ --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader giorgia.andriani22 --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader jacquelienefernandez --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader mmoonstar --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader aishasharma25 --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader alayaf --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader sobhitad --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader sonambajwa --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader tripti_dimri --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader sakshichopraa --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader nikki_tamboli --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout , useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader soniyaofficial123 --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout , useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader prece_jirarachchatapack --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader prece.kaiyokkrokthailand --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader kaiyokkrok.pattaya --login=shyam_it9193 --fast-update --quiet --no-posts --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader filmygyan --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader bollywoodsocietyy --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader viralbhayani --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader bollywoodbubble --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader instantbollywood --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader filmymantramedia --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader bollywoodirect --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader voompla --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader manav.manglani --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader pinkvilla --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader tellymasala --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))
print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
call ("instaloader bolbollywood.in --login=shyam_it9193 --fast-update --stories --quiet --no-posts --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))

# print(f"Printing {sys._getframe().f_lineno}:173")
time.sleep (5)
# call ("instaloader danceplusproofficial_ --login=shyam_it9193 --fast-update --post-filter=\"date_utc >= datetime(2024, 2, 1)\" --stories --request-timeout={} --user-agent=\"{}\"".format(timeout,useragent))

#--filename-pattern={date_local}_IST
# call("instaloader #giorgiaandriani --login=shyam_it9193 --fast-update")
# time.sleep(5)
# call("instaloader imran_offiicial shaansshutterstop --login=shyam_it9193 --fast-update --stories --quiet --no-posts")

# call("instaloader mmoonstar --login=shyam_it9193 --stories")
# --request-timeout 3600
# --request-timeout 86400
