BEGIN TRANSACTION;
DROP TABLE IF EXISTS "ARTICLES";
CREATE TABLE IF NOT EXISTS "ARTICLES" (
	"ARTICLE_URL" TEXT NOT NULL,
	"ARTICLE_DETAIL_URL" TEXT,
	"ARTICLE_TITLE"	TEXT,
	"ARTICLE_THUMBNAIL"	REAL,
	"ARTICLE_PUBLISHED_DATE" REAL,
	"ARTICLE_UPDATED_DATE" TEXT,
	"ARTICLE_CLAIM"	TEXT,
	"ARTICLE_CLAIM_REVIEW" TEXT,
	"ARTICLE_CONTENT" TEXT,
	"ARTICLE_CHECKED_BY" TEXT,
	"ARTICLE_VERDICT" TEXT,
	"ARTICLE_ALT_VERDICT" TEXT,
	"ARTICLE_SITE_ID" INTEGER
	"ARTICLE_IS_PUSHED"	INTEGER
);
DROP TABLE IF EXISTS "SOURCES";
CREATE TABLE IF NOT EXISTS "SOURCES" (
	"SRC_ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"SRC_NAME"	TEXT NOT NULL,
	"SRC_ALT_NAME"	TEXT,
	"SRC_LOGO"	TEXT,
	"SRC_IS_IFCN_APPROVED"	INTEGER,
	"SRC_ADDRESS"	TEXT,
	"SRC_IS_ACTIVE"	INTEGER DEFAULT 1,
	"SRC_COUNTRY"	TEXT,
	"SRC_SUPPORTED_BY"	TEXT,
	"SRC_LANGUAGE"	TEXT,
	"SRC_ADDED_DATE"	TEXT DEFAULT (datetime('now','localtime'))
);
COMMIT;
